name = "spinmacho-casino-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmacho-casino.com.gr"
HMAC_KEY = "f4e75b4ec0954f84904c46b4cfa1f333552a86dc5d58af61b08cc74fa3cccc7e"
COOKIE_NAME = "g8n"
PLAY_PATH = "visit"
BUTTON_ID = "p7feb29dd7e3667010394b5f708a043bb"
GATE_SALT = "80fcba977d32d184"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "y1bw"
CTA_SELECTOR = ".play-button"
